CREATE TABLE [test].[location] (
    [Location_sk]                      INT              NULL,
    [Location_Code_nk]                 INT              NULL,
    [Division_ID]                      INT              NULL,
    [Division]                         NVARCHAR (MAX)   NOT NULL,
    [Region_ID]                        NVARCHAR (MAX)   NOT NULL,
    [Region_Name]                      NVARCHAR (MAX)   NOT NULL,
    [Market_Code]                      INT              NULL,
    [Market_ID]                        INT              NULL,
    [Market]                           NVARCHAR (MAX)   NOT NULL,
    [Location_ID]                      INT              NULL,
    [Location_Name]                    NVARCHAR (MAX)   NOT NULL,
    [Location_Sales_Manager_ID]        INT              NOT NULL,
    [Location_Sales_Manager]           NVARCHAR (MAX)   NOT NULL,
    [Market_Manager_ID]                INT              NOT NULL,
    [Market_Manager]                   NVARCHAR (MAX)   NOT NULL,
    [Label]                            NVARCHAR (MAX)   NOT NULL,
    [Branch_Type]                      NVARCHAR (MAX)   NOT NULL,
    [Phone_Number]                     BIGINT           NULL,
    [Address_1]                        NVARCHAR (MAX)   NOT NULL,
    [Address_2]                        NVARCHAR (MAX)   NOT NULL,
    [City]                             NVARCHAR (MAX)   NOT NULL,
    [State]                            NVARCHAR (MAX)   NOT NULL,
    [Country]                          NVARCHAR (MAX)   NOT NULL,
    [ZIP]                              BIGINT           NULL,
    [Longitude]                        DECIMAL (16, 13) NULL,
    [Latitude]                         DECIMAL (16, 13) NULL,
    [Branch_Announced_Date]            DATE             NULL,
    [Branch_Shut_Down_Date]            DATE             NULL,
    [Active]                           NVARCHAR (MAX)   NOT NULL,
    [Total_Sales_Square_Feet]          INT              NULL,
    [Total_Square_Feet]                INT              NULL,
    [Sales_Conditioned_CC_Square_Feet] INT              NULL,
    [Warehouse_Square_Feet]            INT              NULL,
    [Office_Utility_Square_Feet]       INT              NULL,
    [Admin_Flag]                       NVARCHAR (MAX)   NULL,
    [size]                             NVARCHAR (MAX)   NOT NULL,
    [Time_Zone]                        NVARCHAR (MAX)   NOT NULL
);



