CREATE TABLE [test].[written] (
    [Written_Sales_sk]            INT            NULL,
    [Gross_Sales]                 DECIMAL (7, 2) NULL,
    [Group_SKU_Discount]          DECIMAL (7, 2) NULL,
    [Retail_Reduction_Discount]   DECIMAL (7, 2) NULL,
    [Override_Discount]           DECIMAL (7, 2) NULL,
    [Promotional_Discount]        DECIMAL (7, 2) NULL,
    [Unclassified_Discount]       DECIMAL (7, 2) NULL,
    [Total_Discount]              DECIMAL (7, 2) NULL,
    [Retail_Sales]                DECIMAL (7, 2) NULL,
    [Tax_Amount_1]                DECIMAL (7, 2) NULL,
    [Tax_Amount_2]                DECIMAL (7, 2) NULL,
    [Sales_Units]                 INT            NULL,
    [Written_Time_fk]             INT            NOT NULL,
    [Written_Date_fk]             INT            NOT NULL,
    [Location_fk]                 INT            NOT NULL,
    [Delivery_DC_fk]              INT            NOT NULL,
    [SKU_fk]                      INT            NOT NULL,
    [SKU_Group_fk]                INT            NOT NULL,
    [SKU_Sold_fk]                 INT            NOT NULL,
    [Customer_fk]                 INT            NOT NULL,
    [Designer_Team_fk]            INT            NOT NULL,
    [Merchandising_Promotion_fk]  INT            NOT NULL,
    [Credit_Promotion_fk]         INT            NOT NULL,
    [Override_Reason_fk]          INT            NOT NULL,
    [Transaction_Number_nk]       INT            NULL,
    [Transaction_Line_Number_nk]  INT            NULL,
    [Market_nk]                   INT            NULL,
    [Sales_Status]                NVARCHAR (MAX) NOT NULL,
    [Original_Transaction_Number] INT            NULL,
    [Sales_Type]                  NVARCHAR (MAX) NOT NULL,
    [Transaction_Type]            NVARCHAR (MAX) NOT NULL,
    [Transaction_Sequence]        INT            NULL,
    [Charge_Type]                 NVARCHAR (MAX) NOT NULL,
    [Exchanged_Type]              NVARCHAR (MAX) NOT NULL,
    [Worksheet]                   NVARCHAR (MAX) NOT NULL,
    [Internet_Sale_Flag]          NVARCHAR (MAX) NOT NULL,
    [SourceSystem_fk]             INT            NOT NULL,
    [ETLBatchID_Insert]           INT            NOT NULL,
    [ETLBatchID_Update]           INT            NOT NULL
);



